import { Product } from "@/types/product.types";

export const allProducts: Product[] = [
  {
    id: "1",
    name: "Distributore automatico di sapone 1",
    category: "telecamere",
    description: "Distributore automatico di sapone1",
    price: 12.9,
    imgSrc: "/products/product.png",
    brand: "OnSmart",
    oldPrice: 22.9,
    quantity: 1,
    rating: 5,
    inStock: 10,
    images: ["/products/category1.avif", "/products/product.png"],
    logo: "/products/logo-mach-power.svg",
    variants: [{ id: "2" }, { id: "3" }, { id: "4" }],
  },
  {
    id: "2",
    name: "Distributore automatico di sapone 2",
    category: "telecamere",
    description: "Distributore automatico di sapone2",
    price: 25.9,
    imgSrc: "/products/product.png",
    brand: "OnSmart",
    quantity: 2,
    rating: 4,
    inStock: 5,
    images: ["/products/category1.avif", "/products/product.png"],
    logo: "/products/logo-mach-power.svg",
    variants: [{ id: "1" }, { id: "3" }, { id: "4" }],
  },
  {
    id: "3",
    name: "Distributore automatico di sapone 3",
    category: "telecamere",
    description: "Distributore automatico di sapone3",
    price: 39.9,
    imgSrc: "/products/product.png",
    brand: "OnSmart",
    quantity: 3,
    rating: 3,
    inStock: 2,
    images: ["/products/category1.avif", "/products/product.png"],
    logo: "",
  },
  {
    id: "4",
    name: "Distributore automatico di sapone 4",
    category: "telecamere",
    description: "Distributore automatico di sapone4",
    price: 49.9,
    imgSrc: "/products/product.png",
    brand: "OnSmart",
    quantity: 4,
    oldPrice: 59.9,
    rating: 5,
    inStock: 0,
    images: ["/products/category1.avif", "/products/product.png"],
    logo: "/products/logo-mach-power.svg",
    variants: [{ id: "3" }],
  },
];
