import { Product } from "@/types/product.types";
export const allProducts: Product[] = [
  {
    id: "1",
    brand: "Mach Power",
    name: "Telecamera IP Wi-Fi Full HD",
    description: "Telecamera IP Wi-Fi con visione notturna, audio bidirezionale e app mobile.",
    category: "telecamere",
    price: 59.9,
    oldPrice: 79.9,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 5,
    inStock: 0,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/products/logo-mach-power.svg",
    variants: [{ id: "o1" }, { id: "o2" }, { id: "o3" }],
  },
  {
    id: "2",
    brand: "Uniview",
    name: "Telecamera da Esterno 4 MP",
    description: "Telecamera di sicurezza 4 MP con visione IR 30 m e scocca impermeabile IP67.",
    category: "telecamere",
    price: 119.9,
    // oldPrice: 139.9,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 4,
    inStock: 0,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/logo.svg",
    // variants: [{ id: "o4" }, { id: "o5" }, { id: "o6" }],
  },
  {
    id: "3",
    brand: "Ajax Systems",
    name: "StarterKit Allarme Wireless",
    description:
      "Sistema completo di allarme wireless Ajax con sensore, sirena e app di controllo.",
    category: "sistemi-di-allarme",
    price: 289.0,
    oldPrice: 319.0,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 5,
    inStock: 12,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/products/logo-ajax-systems.svg",
    variants: [{ id: "o7" }, { id: "o8" }, { id: "o9" }],
  },
  {
    id: "4",
    brand: "OnSmart",
    name: "Router 4G LTE Dual Antenna",
    description: "Router 4G LTE ad alte prestazioni con due antenne e connessione stabile.",
    category: "rete",
    price: 69.9,
    oldPrice: 89.9,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 4,
    inStock: 30,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/logo.svg",
    variants: [{ id: "o10" }, { id: "o1" }, { id: "o2" }],
  },
  {
    id: "5",
    brand: "Mach Power",
    name: "Videocitofono Wi-Fi 7″",
    description: "Videocitofono con display da 7 pollici e connessione Wi-Fi per controllo remoto.",
    category: "videocitofoni",
    price: 139.0,
    oldPrice: 169.0,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 5,
    inStock: 20,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/products/logo-mach-power.svg",
    variants: [{ id: "o3" }, { id: "o4" }, { id: "o5" }],
  },
  {
    id: "6",
    brand: "Uniview",
    name: "NVR 8 Canali 4K",
    description: "Registratore di rete Uniview 8 CH con supporto HDD fino a 6 TB.",
    category: "registratori",
    price: 189.0,
    oldPrice: 219.0,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 5,
    inStock: 8,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/logo.svg",
    variants: [{ id: "o7" }, { id: "o8" }, { id: "o9" }],
  },
  {
    id: "7",
    brand: "Ajax Systems",
    name: "Sensore di Movimento PIR",
    description: "Sensore di movimento con rilevamento intelligente e immunità agli animali.",
    category: "sensori",
    price: 79.9,
    oldPrice: 89.9,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 4,
    inStock: 50,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/products/logo-ajax-systems.svg",
    variants: [{ id: "o7" }, { id: "o8" }, { id: "o9" }],
  },
  {
    id: "8",
    brand: "Ajax Systems",
    name: "Sirena Esterna 113 dB",
    description: "Sirena esterna con LED integrato e potenza acustica fino a 113 dB.",
    category: "sirene",
    price: 99.9,
    oldPrice: 119.9,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 5,
    inStock: 25,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/products/logo-ajax-systems.svg",
    variants: [{ id: "o2" }, { id: "o8" }, { id: "o10" }],
  },
  {
    id: "9",
    brand: "OnSmart",
    name: "Switch PoE 8 Porte",
    description: "Switch PoE 8 porte Gigabit per alimentare telecamere IP dal cavo di rete.",
    category: "rete",
    price: 149.9,
    oldPrice: 179.9,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 4,
    inStock: 15,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/products/logo-ajax-systems.svg",
    variants: [{ id: "o3" }, { id: "o6" }, { id: "o9" }],
  },
  {
    id: "10",
    brand: "OnSmart",
    name: "Hub Smart Home ZigBee",
    description: "Hub centrale per casa smart con Wi-Fi, ZigBee e compatibilità Alexa.",
    category: "automazione",
    price: 99.0,
    oldPrice: 129.0,
    imgSrc: "/products/product.png",
    quantity: 1,
    rating: 5,
    inStock: 30,
    images: [
      "/products/product.png",
      "/slider/slide1.webp",
      "/slider/slide2.webp",
      "/slider/slide3.webp",
    ],
    logo: "/products/logo-ajax-systems.svg",
    variants: [{ id: "o1" }, { id: "o4" }, { id: "o9" }, { id: "o10" }],
  },
];

// ========== 2. Інші товари ==========
export const otherProducts: Product[] = allProducts.map((p, i) => ({
  ...p,
  id: `o${i + 1}`,
  price: Number((p.price * 0.9).toFixed(2)),
  name: `${p.name} – Variant`,
  inStock: p.inStock + 10,
}));

// ========== 3. Рекомендовані ==========
export const recomedProducts: Product[] = allProducts.map((p, i) => ({
  ...p,
  id: `r${i + 1}`,
  rating: Math.min(5, p.rating + 0.5),
  oldPrice: p.price + 20,
  price: p.price + 10,
  name: `${p.name} – Reccomended`,
}));
